apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laa-legal-adviser-api
  namespace: laa-legal-adviser-api-production
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-legal-adviser-api-laa-legal-adviser-api-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  tls:
  - hosts:
    - laa-legal-adviser-api-production.apps.live-1.cloud-platform.service.justice.gov.uk
  - hosts:
      - laa-legal-adviser-api-production.cloud-platform.service.justice.gov.uk
  rules:
  - host: laa-legal-adviser-api-production.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: laa-legal-adviser-api
            port:
              number: 80
  - host: laa-legal-adviser-api-production.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: laa-legal-adviser-api
            port: 
              number: 80