#!/bin/bash -e
set -o pipefail

ROOT=$(dirname "$0")
NAMESPACE="$1"
NAMESPACE_DIR="$ROOT/../kubernetes_deploy/$NAMESPACE"

if [ -z "$NAMESPACE" ] ; then
  printf "usage: deploy_to_kubernetes namespace\n"
  echo "namespace is a directory in ../kubernetes_deploy/ directory"
  exit 1
fi

if ! [ -d "$NAMESPACE_DIR" ] ; then
  echo "$NAMESPACE_DIR not found"
  exit 1
fi

if [ -z "$ECR_DEPLOY_IMAGE" ] ; then
  source "$ROOT"/define_build_environment_variables
fi

echo "Deploying $ECR_DEPLOY_IMAGE to $NAMESPACE..."

echo "Running jobs"
COLLECT_STATIC=$NAMESPACE_DIR/collect-static-job.yml 
MIGRATE_DB=$NAMESPACE_DIR/migrate-db-job.yml 

for JOB in $COLLECT_STATIC $MIGRATE_DB
do
  echo "Running $JOB"
  kubectl delete -f $JOB --ignore-not-found
  cat $JOB| \
    kubectl set image app="$ECR_DEPLOY_IMAGE" --filename=/dev/stdin --local --output=yaml | \
    kubectl annotate kubernetes.io/change-cause="$CIRCLE_BUILD_URL" --filename=/dev/stdin --local --output=yaml | \
    kubectl apply --record=false --filename=/dev/stdin
done

echo "Waiting for jobs"
if ! kubectl wait --for=condition=complete -f $COLLECT_STATIC -f $MIGRATE_DB --timeout=180s ; then
  echo "Failed pods:"
  kubectl get pods --field-selector=status.phase=Failed
  FIRST_POD=$(kubectl get pods --field-selector=status.phase=Failed -o=name | head -n 1)
  echo "
Logs for failed pod $FIRST_POD:"
    kubectl logs $FIRST_POD
  exit 1
fi

echo "Deploying app"
CIDR_LAAI=$(curl -s https://raw.githubusercontent.com/ministryofjustice/laa-ip-allowlist/main/cidrs.txt | tr -d ' ' | tr '\n' ',')
CIDR_MONX=$(curl -s https://my.pingdom.com/probes/ipv4 | sed 's/$/\/32/' | tr '\n' ',')
EXTRA_FILE="$ROOT/../kubernetes_deploy/staging/extra-allowlist-cidrs.txt"
CIDR_EXTRA=""
echo "EXTRA_FILE=$EXTRA_FILE"
if [ -f "$EXTRA_FILE" ]; then
  CIDR_EXTRA=$(tr -d ' ' < "$EXTRA_FILE" | tr '\n' ',')
fi
COMBINED_WHITELIST=$(printf "%s%s%s" "$CIDR_LAAI" "$CIDR_MONX" "$CIDR_EXTRA" \
  | sed 's/,,*/,/g; s/^,//; s/,$//')

if [ "$NAMESPACE" == "staging" ]; then
    echo "Applying whitelist with $(echo $COMBINED_WHITELIST | grep -o ',' | wc -l) entries..."
    sed "s|WHITELIST_PLACEHOLDER|${COMBINED_WHITELIST}|g" "$NAMESPACE_DIR/ingress.yml" | \
    kubectl apply -f -
else
    # For other namespaces, just apply the normal ingress without replacement
    kubectl apply -f "$NAMESPACE_DIR/ingress.yml"
fi

cat "$NAMESPACE_DIR/deployment.yml" | \
  kubectl set image app="$ECR_DEPLOY_IMAGE" --filename=/dev/stdin --local --output=yaml | \
  kubectl annotate kubernetes.io/change-cause="$CIRCLE_BUILD_URL" --filename=/dev/stdin --local --output=yaml | \
  kubectl apply --record=false \
    --filename=/dev/stdin \
    --filename="$NAMESPACE_DIR/service.yml" \
    
# Worker queue deployment
cat "$NAMESPACE_DIR/queue_worker_deployment.yml" | \
  kubectl set image worker="$ECR_DEPLOY_IMAGE" --filename=/dev/stdin --local --output=yaml | \
  kubectl annotate kubernetes.io/change-cause="$CIRCLE_BUILD_URL" --filename=/dev/stdin --local --output=yaml | \
  kubectl apply --record=false \
    --filename=/dev/stdin
