apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "<to be filled in deploy_to_kubernetes script>"
  name: laa-legal-adviser-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laa-legal-adviser-api
      tier: api
      env: development
  template:
    metadata:
      labels:
        app: laa-legal-adviser-api
        tier: api
        env: development
        service_area: laa-get-access
        service_team: cla-fala
    spec:
      containers:
      - image: "<to be set by deploy_to_kubernetes>"
        imagePullPolicy: Never
        name: app
        readinessProbe:
          httpGet:
            path: /ping.json
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping.json
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
        ports:
        - containerPort: 80
          name: http
        env:
        - name: LOG_LEVEL
          value: INFO
        - name: DB_USERNAME
          value: postgres
        - name: DB_NAME
          value: laalaa
        - name: DB_HOST
          value: laa-legal-adviser-api-shared-services
        - name: DB_PORT
          value: "5432"
        - name: AMQP_BROKER_URL
          value: "amqp://guest:guest@laa-legal-adviser-api-shared-services:5672//"
