apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "<to be filled in deploy_to_kubernetes script>"
  name: laa-legal-adviser-api-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laa-legal-adviser-api
      tier: worker
      env: development
  template:
    metadata:
      labels:
        app: laa-legal-adviser-api
        tier: worker
        env: development
        service_area: laa-get-access
        service_team: cla-fala
    spec:
      containers:
      - image: "<to be set by deploy_to_kubernetes>"
        imagePullPolicy: Never
        name: worker
        args: ["docker/run_worker.sh"]
        readinessProbe:
          exec:
            command: ["docker/ping_services.sh"]
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["docker/ping_services.sh"]
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
        env:
        - name: WORKER_APP_CONCURRENCY
          value: "2"
        - name: LOG_LEVEL
          value: INFO
        - name: LOG_LEVEL
          value: INFO
        - name: DB_USERNAME
          value: postgres
        - name: DB_NAME
          value: laalaa
        - name: DB_HOST
          value: laa-legal-adviser-api-shared-services
        - name: DB_PORT
          value: "5432"
        - name: CELERY_BROKER_URL
          value: "redis://laa-legal-adviser-api-shared-services:6379"
