apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "<to be filled in deploy_to_kubernetes script>"
  name: laa-legal-adviser-api-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        worker: laa-legal-adviser-api-worker
        env: staging
        service_area: laa-get-access
        service_team: cla-fala
    spec:
      containers:
      - image: "<to be set by deploy_to_kubernetes>"
        imagePullPolicy: Never
        name: worker
        args: ["/home/app/docker/run_worker.sh"]
        env:
        - name: WORKER_APP_CONCURRENCY
          value: "2"
        - name: LOG_LEVEL
          value: INFO
        - name: LOG_LEVEL
          value: INFO
        - name: SECRET_KEY
          value: secret
        - name: DB_USERNAME
          value: postgres
        - name: DB_NAME
          value: laalaa
        - name: DB_HOST
          value: laa-legal-adviser-api-shared-services
        - name: DB_PORT
          value: "5432"
        - name: AMQP_BROKER_URL
          value: "amqp://guest:guest@laa-legal-adviser-api-shared-services:5672//"
