apiVersion: v1
kind: Service
metadata:
  name: laa-legal-adviser-api
  labels:
    app: laa-legal-adviser-api
spec:
  type: NodePort
  ports:
  - port: 8000
    name: http
    targetPort: 8000
    nodePort: 31000
  selector:
    app: laa-legal-adviser-api
    tier: api
---
apiVersion: v1
kind: Service
metadata:
  name: laa-legal-adviser-api-shared-services
spec:
  selector:
    app: laa-legal-adviser-api
    tier: shared-services
  ports:
    - protocol: TCP
      name: postgresql
      port: 5432
      targetPort: 5432
    - protocol: TCP
      name: redis
      port: 6379
      targetPort: 6379
