apiVersion: v1
kind: Service
metadata:
  name: laa-legal-adviser-api
spec:
  type: NodePort
  ports:
  - port: 8000
    name: http
    targetPort: 8000
    nodePort: 31000
  selector:
    app: laa-legal-adviser-api
