apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "<to be filled in deploy_to_kubernetes script>"
  name: laa-legal-adviser-api-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laa-legal-adviser-api
      tier: worker
      env: staging
  template:
    metadata:
      labels:
        app: laa-legal-adviser-api
        tier: worker
        env: staging
        service_area: laa-get-access
        service_team: cla-fala
    spec:
      serviceAccountName: laa-legal-adviser-api-staging-irsa-sevice-account
      containers:
      - image: "<to be set by deploy_to_kubernetes>"
        name: worker
        args: ["docker/run_worker.sh"]
        env:
        - name: ENV
          value: staging
        - name: WORKER_APP_CONCURRENCY
          value: "8"
        - name: LOG_LEVEL
          value: INFO
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: SECRET_KEY
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: dsn
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-14
              key: url
        - name: CELERY_PREDEFINED_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: sqs
              key: sqs_id
