name: Workflow to build, test and deploy application

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.image }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build image
        run: docker build -t myapp-ci:${{ github.sha }} .

      - name: Save image name
        id: meta
        run: echo "image=myapp-ci:${{ github.sha }}" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Run lint
        run: |
          docker run --rm ${{ needs.build-image.outputs.image }} \
            pre-commit run --all-files