# Generated by Django 2.2.10 on 2021-08-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("advisers", "0009_auto_20210811_1709")]

    operations = [migrations.AddField(model_name="import", name="failure_reason", field=models.TextField(null=True))]
