# Generated by Django 2.2.10 on 2021-09-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("advisers", "0010_import_failure_reason")]

    operations = [
        migrations.AddField(model_name="import", name="completed", field=models.DateTimeField(null=True)),
        migrations.AddField(
            model_name="import", name="created", field=models.DateTimeField(auto_now_add=True, null=True)
        ),
        migrations.AlterField(model_name="import", name="started", field=models.DateTimeField(null=True)),
        migrations.AlterField(
            model_name="import",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "created"),
                    ("RUNNING", "running"),
                    ("SUCCESS", "success"),
                    ("FAILURE", "failure"),
                    ("ABORTED", "aborted"),
                ],
                max_length=7,
            ),
        ),
    ]
